apiVersion: v1
kind: Service 
metadata:
  name: sparta-app
  namespace: default
spec:
  ports:
    - nodePort: 30002
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: sparta-app
  type: NodePort
  #type: LoadBalancer